// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQEJ--xNA4wG_BM09pOvDpwJUtLATklRw',
    appId: '1:410682681765:web:49fea658c3eacb576d204c',
    messagingSenderId: '410682681765',
    projectId: 'homework2-de10f',
    authDomain: 'homework2-de10f.firebaseapp.com',
    storageBucket: 'homework2-de10f.firebasestorage.app',
    measurementId: 'G-2TT66LK7FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKiiBjWhUt0lrkFDhIzBLH8U9w7jhiVcE',
    appId: '1:410682681765:android:b8fe8236684702fb6d204c',
    messagingSenderId: '410682681765',
    projectId: 'homework2-de10f',
    storageBucket: 'homework2-de10f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMjdu0n-zDsiGxN2m5UaVZkVFJiafx8I',
    appId: '1:410682681765:ios:2cc564edd4211b336d204c',
    messagingSenderId: '410682681765',
    projectId: 'homework2-de10f',
    storageBucket: 'homework2-de10f.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMjdu0n-zDsiGxN2m5UaVZkVFJiafx8I',
    appId: '1:410682681765:ios:2cc564edd4211b336d204c',
    messagingSenderId: '410682681765',
    projectId: 'homework2-de10f',
    storageBucket: 'homework2-de10f.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQEJ--xNA4wG_BM09pOvDpwJUtLATklRw',
    appId: '1:410682681765:web:35c0035fa800f5a16d204c',
    messagingSenderId: '410682681765',
    projectId: 'homework2-de10f',
    authDomain: 'homework2-de10f.firebaseapp.com',
    storageBucket: 'homework2-de10f.firebasestorage.app',
    measurementId: 'G-5WCNX767K8',
  );
}
